# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import var


class Ui_venAviso(object):
    def setupUi(self, venAviso):
        venAviso.setObjectName("venAviso")
        venAviso.resize(400, 167)
        venAviso.setModal(True)
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(venAviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(120, 110, 161, 32))
        self.btnBoxAviso.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxAviso.setCenterButtons(True)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        var.lblMensaje = QtWidgets.QLabel(venAviso)
        var.lblMensaje.setGeometry(QtCore.QRect(60, 80, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        var.lblMensaje.setFont(font)
        var.lblMensaje.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        var.lblMensaje.setObjectName("lblMensaje")
        self.lblImgSalir = QtWidgets.QLabel(venAviso)
        self.lblImgSalir.setGeometry(QtCore.QRect(180, 20, 41, 41))
        self.lblImgSalir.setText("")
        self.lblImgSalir.setPixmap(QtGui.QPixmap("img/iconoSalir.png"))
        self.lblImgSalir.setScaledContents(True)
        self.lblImgSalir.setObjectName("lblImgSalir")

        self.retranslateUi(venAviso)
        self.btnBoxAviso.accepted.connect(venAviso.accept)
        self.btnBoxAviso.rejected.connect(venAviso.reject)
        QtCore.QMetaObject.connectSlotsByName(venAviso)

    def retranslateUi(self, venAviso):
        _translate = QtCore.QCoreApplication.translate
        venAviso.setWindowTitle(_translate("venAviso", "Aviso"))
        var.lblMensaje.setText(_translate("venAviso", "¿Está seguro que quiere salir de la aplicación?"))
import iconoSalir_rc
