# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venDni.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venAvisoDni(object):
    def setupUi(self, venAvisoDni):
        venAvisoDni.setObjectName("venAvisoDni")
        venAvisoDni.setWindowModality(QtCore.Qt.WindowModal)
        venAvisoDni.resize(322, 119)
        venAvisoDni.setModal(True)
        self.label = QtWidgets.QLabel(venAvisoDni)
        self.label.setGeometry(QtCore.QRect(80, 10, 211, 61))
        self.label.setObjectName("label")
        self.lblImgAviso = QtWidgets.QLabel(venAvisoDni)
        self.lblImgAviso.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.lblImgAviso.setText("")
        self.lblImgAviso.setPixmap(QtGui.QPixmap(":/iconoSalir/iconoSalir.png"))
        self.lblImgAviso.setObjectName("lblImgAviso")
        self.btnBoxSalir = QtWidgets.QDialogButtonBox(venAvisoDni)
        self.btnBoxSalir.setGeometry(QtCore.QRect(150, 70, 141, 32))
        self.btnBoxSalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxSalir.setCenterButtons(True)
        self.btnBoxSalir.setObjectName("btnBoxSalir")

        self.retranslateUi(venAvisoDni)
        QtCore.QMetaObject.connectSlotsByName(venAvisoDni)

    def retranslateUi(self, venAvisoDni):
        _translate = QtCore.QCoreApplication.translate
        venAvisoDni.setWindowTitle(_translate("venAvisoDni", "Aviso DNI"))
        self.label.setText(_translate("venAvisoDni", "El DNI que intenta introducir no es correcto"))
import iconoSalir_rc
