# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venSalir(object):
    def setupUi(self, venSalir):
        venSalir.setObjectName("venSalir")
        venSalir.resize(400, 152)
        venSalir.setModal(True)
        self.lblMensajeSalir = QtWidgets.QLabel(venSalir)
        self.lblMensajeSalir.setGeometry(QtCore.QRect(60, 70, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMensajeSalir.setFont(font)
        self.lblMensajeSalir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMensajeSalir.setObjectName("lblMensajeSalir")
        self.lblImgSalir = QtWidgets.QLabel(venSalir)
        self.lblImgSalir.setGeometry(QtCore.QRect(180, 10, 41, 41))
        self.lblImgSalir.setText("")
        self.lblImgSalir.setPixmap(QtGui.QPixmap("img/iconoSalir.png"))
        self.lblImgSalir.setScaledContents(True)
        self.lblImgSalir.setObjectName("lblImgSalir")
        self.btnAceptar = QtWidgets.QPushButton(venSalir)
        self.btnAceptar.setGeometry(QtCore.QRect(120, 110, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnBoxSalir = QtWidgets.QButtonGroup(venSalir)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.btnBoxSalir.addButton(self.btnAceptar)
        self.btnCancelar = QtWidgets.QPushButton(venSalir)
        self.btnCancelar.setGeometry(QtCore.QRect(210, 110, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnBoxSalir.addButton(self.btnCancelar)

        self.retranslateUi(venSalir)
        QtCore.QMetaObject.connectSlotsByName(venSalir)

    def retranslateUi(self, venSalir):
        _translate = QtCore.QCoreApplication.translate
        venSalir.setWindowTitle(_translate("venSalir", "¿Desea salir?"))
        self.lblMensajeSalir.setText(_translate("venSalir", "¿Está seguro que quiere salir de la aplicación?"))
        self.btnAceptar.setText(_translate("venSalir", "Aceptar"))
        self.btnCancelar.setText(_translate("venSalir", "Cancelar"))
import iconoSalir_rc
